class Permissions {
    static CREATE_USER = "CREATE_USER";

    static CREATE_ORDER = "CREATE_ORDER";
    static READ_ORDER = "READ_ORDER";
    static UPDATE_ORDER = "UPDATE_ORDER";
    static DELETE_ORDER = "DELETE_ORDER";

    static READ_PRODUCT = "READ_PRODUCT";
    static UPDATE_PRODUCT = "UPDATE_PRODUCT";

    static CREATE_SUPPLIER = "CREATE_SUPPLIER";
    static READ_SUPPLIER = "READ_SUPPLIER";
    static UPDATE_SUPPLIER = "UPDATE_SUPPLIER";
    static DELETE_SUPPLIER = "DELETE_SUPPLIER";

    static CREATE_SHIPPING = "CREATE_SHIPPING";
    static READ_SHIPPING = "READ_SHIPPING";
    static UPDATE_SHIPPING = "UPDATE_SHIPPING";
    static DELETE_SHIPPING = "DELETE_SHIPPING";

    static CREATE_PAYMENT = "CREATE_PAYMENT";
    static READ_PAYMENT = "READ_PAYMENT";
    static UPDATE_PAYMENT = "UPDATE_PAYMENT";
    static DELETE_PAYMENT = "DELETE_PAYMENT";
}

export default Permissions;